# Generated by Django 4.2.1 on 2023-05-17 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iblog', '0003_contactenquiry'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactenquiry',
            name='message',
            field=models.TextField(default=2),
            preserve_default=False,
        ),
    ]
