# Generated by Django 4.2.1 on 2023-05-19 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iblog', '0004_contactenquiry_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='HandleRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('cardnumber', models.IntegerField()),
                ('date1', models.IntegerField()),
                ('date2', models.IntegerField()),
                ('cvc', models.IntegerField()),
            ],
        ),
    ]
