# Generated by Django 4.2.1 on 2023-05-22 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iblog', '0007_comments_delete_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='author',
            new_name='user',
        ),
    ]
