# Generated by Django 4.2.1 on 2023-05-23 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iblog', '0012_comment_delete_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='user',
        ),
    ]
